name: build

on: [push]

jobs:
  env:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - run: |
          set -exou pipefail
          GITHUB_ID_TOKEN="$(curl -sLS -H "User-Agent: actions/oidc-client" -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=jfrog-github" | jq -r .value)"
          echo "${GITHUB_ID_TOKEN}" | cut -d. -f2 | jq
